//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class acao
    {
        public acao()
        {
            this.pagina_acao = new HashSet<pagina_acao>();
        }
    
        public int aca_id_acao { get; set; }
        public string aca_ds_acao { get; set; }
        public string aca_ds_alias { get; set; }
        public int aca_vl_ordem { get; set; }
    
        public virtual ICollection<pagina_acao> pagina_acao { get; set; }
    }
}
