//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class acidente_colaborador
    {
        public int acc_id_acidente_colaborador { get; set; }
        public int acc_id_acidente { get; set; }
        public int acc_id_obra_colaborador { get; set; }
        public string acc_st_atastamento { get; set; }
    
        public virtual acidente acidente { get; set; }
        public virtual obra_colaborador obra_colaborador { get; set; }
    }
}
