//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class acidente
    {
        public acidente()
        {
            this.acidente_colaborador = new HashSet<acidente_colaborador>();
        }
    
        public int aci_id_acidente { get; set; }
        public int aci_id_tarefa { get; set; }
        public string aci_ds_acidente { get; set; }
        public Nullable<System.DateTime> aci_dt_data_hora { get; set; }
        public string aci_st_afastamento { get; set; }
    
        public virtual ICollection<acidente_colaborador> acidente_colaborador { get; set; }
        public virtual tarefa tarefa { get; set; }
    }
}
