//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class assinatura_rdo
    {
        public int ass_id_assinatura { get; set; }
        public int ass_id_obra_colaborador_assinante { get; set; }
        public int ass_id_rdo { get; set; }
        public string ass_ds_ip { get; set; }
        public Nullable<System.DateTime> ass_dt_assinatura { get; set; }
    
        public virtual obra_colaborador obra_colaborador { get; set; }
        public virtual rdo rdo { get; set; }
    }
}
