//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargo
    {
        public cargo()
        {
            this.obra_colaborador = new HashSet<obra_colaborador>();
        }
    
        public int car_id_cargo { get; set; }
        public string car_ds_cargo { get; set; }
    
        public virtual ICollection<obra_colaborador> obra_colaborador { get; set; }
    }
}
