//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class efetivo_status
    {
        public efetivo_status()
        {
            this.efetivo = new HashSet<efetivo>();
        }
    
        public int est_id_efetivo_status { get; set; }
        public string est_ds_efetivo_status { get; set; }
        public string est_ds_color { get; set; }
    
        public virtual ICollection<efetivo> efetivo { get; set; }
    }
}
