//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class efetivo
    {
        public int efe_id_efetivo { get; set; }
        public int efe_id_obra { get; set; }
        public int efe_id_obra_colaborador { get; set; }
        public int efe_id_efetivo_status { get; set; }
        public System.DateTime efe_data { get; set; }
    
        public virtual obra obra { get; set; }
        public virtual obra_colaborador obra_colaborador { get; set; }
        public virtual efetivo_status efetivo_status { get; set; }
    }
}
