//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipamento
    {
        public equipamento()
        {
            this.obra_equipamento = new HashSet<obra_equipamento>();
        }
    
        public int equ_id_equipamento { get; set; }
        public string equ_ds_equipamento { get; set; }
        public string equ_ds_marca { get; set; }
        public string equ_ds_modelo { get; set; }
        public int equ_id_tipo_equipamento { get; set; }
        public string equ_ds_imagem { get; set; }
    
        public virtual tipo_equipamento tipo_equipamento { get; set; }
        public virtual ICollection<obra_equipamento> obra_equipamento { get; set; }
    }
}
