//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class etapa
    {
        public etapa()
        {
            this.tarefa = new HashSet<tarefa>();
        }
    
        public int eta_id_etapa { get; set; }
        public string eta_ds_etapa { get; set; }
        public int eta_nr_orderm { get; set; }
        public int eta_id_obra { get; set; }
    
        public virtual obra obra { get; set; }
        public virtual ICollection<tarefa> tarefa { get; set; }
    }
}
