//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo
    {
        public grupo()
        {
            this.grupo_pagina_acao = new HashSet<grupo_pagina_acao>();
            this.obra_colaborador = new HashSet<obra_colaborador>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int gru_id_grupo { get; set; }
        public string gru_nm_nome { get; set; }
        public int gru_id_menu { get; set; }
        public Nullable<int> gru_id_licenca { get; set; }
        public Nullable<int> gru_st_diretor { get; set; }
        public Nullable<int> gru_st_contratante { get; set; }
    
        public virtual licenca licenca { get; set; }
        public virtual menu menu { get; set; }
        public virtual ICollection<grupo_pagina_acao> grupo_pagina_acao { get; set; }
        public virtual ICollection<obra_colaborador> obra_colaborador { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
