//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_pagina_acao
    {
        public int gpa_id_grupo_pagina_acao { get; set; }
        public int gpa_id_grupo { get; set; }
        public int gpa_id_pagina_acao { get; set; }
    
        public virtual grupo grupo { get; set; }
        public virtual pagina_acao pagina_acao { get; set; }
    }
}
