//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class historico_login
    {
        public int col_id_colaborador { get; set; }
        public string col_nr_cpf { get; set; }
        public string col_nm_colaborador { get; set; }
        public string col_ds_email { get; set; }
        public Nullable<int> obr_id_obra { get; set; }
        public string obr_ds_obra { get; set; }
        public System.DateTime data_login { get; set; }
    }
}
