//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class historico_tarefa_rdo
    {
        public historico_tarefa_rdo()
        {
            this.historico_tarefa_colaborador = new HashSet<historico_tarefa_colaborador>();
            this.historico_tarefa_equipamento = new HashSet<historico_tarefa_equipamento>();
        }
    
        public int his_id_historico_tarefa_rdo { get; set; }
        public int his_id_tarefa { get; set; }
        public int his_id_rdo { get; set; }
        public int his_id_status { get; set; }
        public Nullable<System.DateTime> his_dt_data { get; set; }
        public string his_ds_foto { get; set; }
        public string his_ds_comentario { get; set; }
        public int his_nr_horas_trabalhadas { get; set; }
    
        public virtual ICollection<historico_tarefa_colaborador> historico_tarefa_colaborador { get; set; }
        public virtual ICollection<historico_tarefa_equipamento> historico_tarefa_equipamento { get; set; }
        public virtual tarefa tarefa { get; set; }
        public virtual rdo rdo { get; set; }
        public virtual status_tarefa status_tarefa { get; set; }
    }
}
