//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class improdutividade
    {
        public improdutividade()
        {
            this.rdo = new HashSet<rdo>();
        }
    
        public int imp_id_improdutividade { get; set; }
        public bool imp_st_clima { get; set; }
        public bool imp_st_material { get; set; }
        public bool imp_st_paralizacao { get; set; }
        public bool imp_st_equipamento { get; set; }
        public bool imp_st_contratante { get; set; }
        public bool imp_st_fornecedores { get; set; }
        public bool imp_st_maodeobra { get; set; }
        public bool imp_st_projeto { get; set; }
        public bool imp_st_planejamento { get; set; }
        public bool imp_st_acidentes { get; set; }
    
        public virtual ICollection<rdo> rdo { get; set; }
    }
}
