//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class laudo
    {
        public int laudo_id_laudo { get; set; }
        public int laudo_id_status { get; set; }
        public int laudo_id_obra { get; set; }
        public System.DateTime laudo_dt_laudo { get; set; }
        public string laudo_ds_comentario_assinatura { get; set; }
        public Nullable<int> laudo_id_colaborador { get; set; }
        public Nullable<System.DateTime> laudo_dt_geracao { get; set; }
        public string laudo_tp_comentario_assinatura { get; set; }
        public string laudo_ds_comentario_geracao { get; set; }
        public string laudo_tp_comentario_geracao { get; set; }
        public Nullable<bool> laudo_tp_nivel_cloro { get; set; }
        public Nullable<bool> laudo_tp_ph { get; set; }
        public Nullable<bool> laudo_tp_limpidez { get; set; }
        public Nullable<bool> laudo_tp_superficie { get; set; }
        public Nullable<bool> laudo_tp_fundo { get; set; }
        public Nullable<bool> laudo_tp_nivel_cloro_2 { get; set; }
        public Nullable<bool> laudo_tp_nivel_bacterias { get; set; }
        public Nullable<bool> laudo_tp_nivel_proliferacao { get; set; }
    
        public virtual colaborador colaborador { get; set; }
        public virtual status_rdo status_rdo { get; set; }
        public virtual ICollection<rdo_imagem> rdo_imagem { get; set; }
        public virtual obra obra { get; set; }
    }
}
