//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class licenca
    {
        public licenca()
        {
            this.empresa = new HashSet<empresa>();
            this.grupo = new HashSet<grupo>();
        }
    
        public int lic_id_licenca { get; set; }
        public string lic_ds_licenca { get; set; }
        public Nullable<int> lic_nr_qtd_usuarios { get; set; }
        public Nullable<int> lic_nr_qtd_obras { get; set; }
        public int lic_qtd_imagens_tarefas { get; set; }
        public int lic_qtd_tarefas_obra { get; set; }
        public bool lic_st_permite_logo_rdo { get; set; }
        public string lic_id_licenca_loja { get; set; }
    
        public virtual ICollection<empresa> empresa { get; set; }
        public virtual ICollection<grupo> grupo { get; set; }
    }
}
