//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_pagina
    {
        public menu_pagina()
        {
            this.menu_pagina1 = new HashSet<menu_pagina>();
        }
    
        public int mpa_id_menu_pagina { get; set; }
        public int mpa_id_menu { get; set; }
        public int mpa_id_pagina { get; set; }
        public Nullable<int> mpa_id_pagina_pai { get; set; }
        public int mpa_vl_nivel { get; set; }
        public int mpa_vl_ordem { get; set; }
        public string mpa_ds_class { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual ICollection<menu_pagina> menu_pagina1 { get; set; }
        public virtual menu_pagina menu_pagina2 { get; set; }
        public virtual pagina pagina { get; set; }
    }
}
