//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipio
    {
        public municipio()
        {
            this.colaborador = new HashSet<colaborador>();
            this.empresa = new HashSet<empresa>();
            this.obra = new HashSet<obra>();
        }
    
        public int mun_id_municipio { get; set; }
        public int mun_id_uf { get; set; }
        public string mun_ds_municipio { get; set; }
    
        public virtual ICollection<colaborador> colaborador { get; set; }
        public virtual ICollection<empresa> empresa { get; set; }
        public virtual uf uf { get; set; }
        public virtual ICollection<obra> obra { get; set; }
    }
}
