//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagina
    {
        public pagina()
        {
            this.menu_pagina = new HashSet<menu_pagina>();
            this.pagina_acao = new HashSet<pagina_acao>();
        }
    
        public int pag_id_pagina { get; set; }
        public string pag_ds_url { get; set; }
        public string pag_nm_titulo { get; set; }
        public string pag_ds_alias { get; set; }
        public int pag_st_status { get; set; }
    
        public virtual ICollection<menu_pagina> menu_pagina { get; set; }
        public virtual ICollection<pagina_acao> pagina_acao { get; set; }
    }
}
