//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagina_acao
    {
        public pagina_acao()
        {
            this.grupo_pagina_acao = new HashSet<grupo_pagina_acao>();
        }
    
        public int paa_id_pagina_acao { get; set; }
        public int paa_id_pagina { get; set; }
        public int paa_id_acao { get; set; }
    
        public virtual acao acao { get; set; }
        public virtual ICollection<grupo_pagina_acao> grupo_pagina_acao { get; set; }
        public virtual pagina pagina { get; set; }
    }
}
