//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil_assinante
    {
        public int per_id_perfil { get; set; }
        public string per_ds_perfil { get; set; }
        public Nullable<int> per_nr_qtd_obras { get; set; }
        public byte[] per_st_acesso_dashboard { get; set; }
        public byte[] per_st_assina_rdo { get; set; }
    }
}
