//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class ramo
    {
        public ramo()
        {
            this.empresa = new HashSet<empresa>();
        }
    
        public int ram_id_ramo { get; set; }
        public string ram_ds_ramo { get; set; }
        public string ram_id_ramo_loja { get; set; }
    
        public virtual ICollection<empresa> empresa { get; set; }
    }
}
