//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdo_imagem
    {
        public int rim_id_rdo_imagem { get; set; }
        public int rim_id_rdo { get; set; }
        public int rim_id_imagem { get; set; }
    
        public virtual imagem imagem { get; set; }
        public virtual rdo rdo { get; set; }
    }
}
