//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdo_tarefa
    {
        public int rta_id_rta { get; set; }
        public int rta_id_rdo { get; set; }
        public int rta_id_tarefa { get; set; }
    
        public virtual rdo rdo { get; set; }
        public virtual tarefa tarefa { get; set; }
    }
}
