//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_tarefa
    {
        public status_tarefa()
        {
            this.historico_tarefa_rdo = new HashSet<historico_tarefa_rdo>();
            this.tarefa = new HashSet<tarefa>();
        }
    
        public int stt_id_status { get; set; }
        public string stt_ds_status { get; set; }
    
        public virtual ICollection<historico_tarefa_rdo> historico_tarefa_rdo { get; set; }
        public virtual ICollection<tarefa> tarefa { get; set; }
    }
}
