//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_equipamento
    {
        public tipo_equipamento()
        {
            this.equipamento = new HashSet<equipamento>();
        }
    
        public int teq_id_tipo_equipamento { get; set; }
        public string teq_nm_tipo_equipamento { get; set; }
        public string teq_ds_tipo_equipamento { get; set; }
    
        public virtual ICollection<equipamento> equipamento { get; set; }
    }
}
