//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class uf
    {
        public uf()
        {
            this.municipio = new HashSet<municipio>();
        }
    
        public int ufe_id_uf { get; set; }
        public string ufe_ds_uf { get; set; }
        public string ufe_ds_sigla { get; set; }
    
        public virtual ICollection<municipio> municipio { get; set; }
    }
}
