//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaudosPiscinasClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int usu_id_usuario { get; set; }
        public string usu_ds_email { get; set; }
        public string usu_ds_senha { get; set; }
        public int usu_id_grupo { get; set; }
        public Nullable<int> usu_st_status { get; set; }
        public Nullable<int> usu_st_alterar_senha { get; set; }
    
        public virtual grupo grupo { get; set; }
    }
}
